### ISSUE TITLE
Never call onConnected after update StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by odinnou** [aspnet/SignalR-Redis#30]
Hello,
I have recently updated the StackExchange.Redis.StrongName package from v1.0.322 to v1.2.1.

But after this package update, the hubs became inaccessible :( OnConnected was never been call.
I thought it was a regression from my code, but after few hours I tried to downgrade for back to v1.0.322 of the  StackExchange.Redis.StrongName package and then the hub rework like a charm.

I don't get any exception or any message so it was hard to find.

I upgrade this package because I want to be up to date on all my Nuget packages of my Solution.

Is-it a known bug ?

Thanks in advance

**Comment by BrennanConroy** [comment]
This repo is no longer being used for SignalR work, see the README https://github.com/aspnet/SignalR-Redis/blob/dev/README.md
We have moved to https://github.com/aspnet/SignalR
